import { Icons } from "../Assets/icons";

const data = [
  { Name: ".Net", Icon: Icons.Net, Color: "#EBEBEB" },
  { Name: "Angular", Icon: Icons.Angular, Color: "#E02F23" },
  { Name: "css3", Icon: Icons.Css, Color: "#F0DB4F" },
  { Name: "React", Icon: Icons.React, Color: "#404137" },
  { Name: "VSCode", Icon: Icons.VsCode, Color: "#404137" },
  { Name: "Visual Studio", Icon: Icons.VisualStudio, Color: "#04AA" },
  { Name: "Javascript", Icon: Icons.Javascript, Color: "#9C0C55" },
  { Name: "C#", Icon: Icons.Csharp, Color: "#23C2EE" },
  { Name: "Typescript", Icon: Icons.Typescript, Color: "#404137" },
  { Name: "Git", Icon: Icons.Git, Color: "#EBEBEB" },
  { Name: ".Net Core", Icon: Icons.NetCore, Color: "#EBEBEB" },
  { Name: "Nodejs", Icon: Icons.Nodejs, Color: "#404137" },
  { Name: "Sl Server", Icon: Icons.Slserver, Color: "#EBEBEB" },
  { Name: "Jira", Icon: Icons.Jira, Color: "#04AA" },
  { Name: "Gitlab", Icon: Icons.Gitlab, Color: "#FF8A51" },
  { Name: "Confluence", Icon: Icons.Confluence, Color: "#EBEBEB" },
  { Name: "Juery", Icon: Icons.Juery, Color: "#FF8A51" },
  { Name: "Bamboo", Icon: Icons.Bamboo, Color: "#23C2EE" },
  { Name: "Docker", Icon: Icons.Docker, Color: "#EBEBEB" },
  { Name: "Sass", Icon: Icons.Sass, Color: "#9C0C55" },
  { Name: "Python", Icon: Icons.Python, Color: "#23C2EE" },
  { Name: "Mysl", Icon: Icons.Mysl, Color: "#F0DB4F" },
  { Name: "Bootstrap", Icon: Icons.Bootstrap, Color: "#F0DB4F" },
  { Name: "Html5", Icon: Icons.Html, Color: "#FF8A51" },
  { Name: "Azure", Icon: Icons.Azure, Color: "#404137" },
  { Name: "Bitbucket", Icon: Icons.Bitbucket, Color: "#04AA" },
  { Name: "", Icon: Icons.Figma, Color: "#404137" },
  { Name: "", Icon: "", Color: "#404137" },
  { Name: "", Icon: "", Color: "#F0DB4F" },
  { Name: "", Icon: "", Color: "#EBEBEB" },
  { Name: "", Icon: "", Color: "#404137" },
  { Name: "", Icon: "", Color: "#04AA" },
  { Name: "", Icon: "", Color: "#FF8A51" },
];

export default data;
